author: jrydberg
kind: gilliam#release
message: null
name: '3'
services:
  _store:
    command: null
    env: {}
    image: gilliam/etcd
    options: {}
    ports:
    - 4001
    - 7001
  _worker:
    command: bin/worker
    env: {}
    image: gilliam/scheduler-_worker:a0a786d6bd8e6ebdc8a1139d0d8f1673
    options: {}
    ports: []
  api:
    command: bin/api
    env: {}
    image: gilliam/scheduler-api:a0a786d6bd8e6ebdc8a1139d0d8f1673
    options: {}
    ports:
    - 80
